[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings=[
    "@aa/=lib/account-abstraction/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts",
    "@systemContracts/=lib/foundry-era-contracts/src/system-contracts/",
]
is-system = true
via-ir = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
